export const CONFIG = {
  APPWRITE_PROJECT_ID: import.meta.env.VITE_APPWRITE_PROJECT_ID,
  APPWRITE_ENDPOINT: import.meta.env.VITE_APPWRITE_ENDPOINT,
  APPWRITE_DATABASE: import.meta.env.VITE_APPWRITE_DATABASE,
  APPWRITE_COLLECTION_WISHES: import.meta.env.VITE_APPWRITE_COLLECTION_WISHES,
  APPWRITE_COLLECTION_WISHLISTS: import.meta.env
    .VITE_APPWRITE_COLLECTION_WISHLISTS,
  APPWRITE_STORAGE_BUCKET: import.meta.env.VITE_APPWRITE_STORAGE_BUCKET,
};
