export const wishes = [
  {
    $id: "wish1",
    $collectionId: "wishes",
    $databaseId: "mainDB",
    $createdAt: "2025-07-18T10:00:00Z",
    $updatedAt: "2025-07-18T10:00:00Z",
    $permissions: [],
    title: "Noise Cancelling Headphones",
    description: "High-quality wireless headphones with noise cancellation.",
    shopURL: "https://example.com/headphones",
    price: 299.99,
    currency: "USD",
    isArchived: false,
    ownerId: "user1",
    isBooked: false,
    wishlistId: "wishlist1",
    imageURL:
      "https://anyplaceholder.com/placeholder?width=800&height=600&bg=ff573366&color=fff&text=wish+1&fontSize=28&radius=5&format=png&retina=true",
    isPrivate: false,
    canReadId: [],
    canEditId: [],
  },
  {
    $id: "wish2",
    $collectionId: "wishes",
    $databaseId: "mainDB",
    $createdAt: "2025-07-18T10:01:00Z",
    $updatedAt: "2025-07-18T10:01:00Z",
    $permissions: [],
    title: "Kindle Paperwhite",
    description: "E-reader with built-in light and waterproof design.",
    shopURL: "https://example.com/kindle",
    price: 139.99,
    currency: "USD",
    isArchived: false,
    ownerId: "user2",
    bookerId: "user5",
    isBooked: true,
    wishlistId: "wishlist1",
    imageURL:
      "https://anyplaceholder.com/placeholder?width=750&height=500&bg=00ccaa66&color=ffffff&text=wish+2&fontSize=24&radius=10&format=png&retina=true",
    isPrivate: false,
    canReadId: ["user5"],
    canEditId: ["user2"],
  },
  {
    $id: "wish3",
    $collectionId: "wishes",
    $databaseId: "mainDB",
    $createdAt: "2025-07-18T10:02:00Z",
    $updatedAt: "2025-07-18T10:02:00Z",
    $permissions: [],
    title: "LEGO Architecture Set",
    description: "A model of New York City skyline.",
    shopURL: "https://example.com/lego",
    price: 59.99,
    currency: "USD",
    isArchived: false,
    ownerId: "user3",
    isBooked: false,
    wishlistId: "wishlist2",
    imageURL:
      "https://anyplaceholder.com/placeholder?width=700&height=500&bg=aa33ff66&color=ffffff&text=wish+3&fontSize=22&radius=8&format=png&retina=true",
    isPrivate: false,
    canReadId: [],
    canEditId: [],
  },
  {
    $id: "wish4",
    $collectionId: "wishes",
    $databaseId: "mainDB",
    $createdAt: "2025-07-18T10:03:00Z",
    $updatedAt: "2025-07-18T10:03:00Z",
    $permissions: [],
    title: "Smart Coffee Maker",
    description: "WiFi-enabled coffee maker for programmable brewing.",
    shopURL: "https://example.com/coffee-maker",
    price: 129.99,
    currency: "USD",
    isArchived: false,
    ownerId: "user4",
    isBooked: false,
    wishlistId: "wishlist3",
    imageURL:
      "https://anyplaceholder.com/placeholder?width=820&height=620&bg=0099cc66&color=fff&text=wish+4&fontSize=26&radius=6&format=png&retina=true",
    isPrivate: false,
    canReadId: [],
    canEditId: ["user4"],
  },
  {
    $id: "wish5",
    $collectionId: "wishes",
    $databaseId: "mainDB",
    $createdAt: "2025-07-18T10:04:00Z",
    $updatedAt: "2025-07-18T10:04:00Z",
    $permissions: [],
    title: "Vinyl Record Player",
    description: "Classic turntable with modern features.",
    shopURL: "https://example.com/turntable",
    price: 89.99,
    currency: "USD",
    isArchived: false,
    ownerId: "user5",
    isBooked: false,
    wishlistId: "wishlist4",
    imageURL:
      "https://anyplaceholder.com/placeholder?width=790&height=580&bg=ee004466&color=fff&text=wish+5&fontSize=30&radius=12&format=png&retina=true",
    isPrivate: true,
    canReadId: ["user1", "user3"],
    canEditId: ["user5"],
  },
  {
    $id: "wish6",
    $collectionId: "wishes",
    $databaseId: "mainDB",
    $createdAt: "2025-07-18T10:05:00Z",
    $updatedAt: "2025-07-18T10:05:00Z",
    $permissions: [],
    title: "Sample Wish Title 6",
    description: "Description for sample wish 6.",
    shopURL: "https://example.com/item6",
    price: 147.27,
    currency: "USD",
    isArchived: false,
    ownerId: "user9",
    bookerId: null,
    isBooked: true,
    wishlistId: "wishlist2",
    imageURL:
      "https://anyplaceholder.com/placeholder?width=828&height=675&bg=817A3B66&color=fff&text=wish+6&fontSize=25&radius=7&format=png&retina=true",
    isPrivate: true,
    canReadId: [],
    canEditId: ["user5", "user4"],
  },
  {
    $id: "wish7",
    $collectionId: "wishes",
    $databaseId: "mainDB",
    $createdAt: "2025-07-18T10:06:00Z",
    $updatedAt: "2025-07-18T10:06:00Z",
    $permissions: [],
    title: "Sample Wish Title 7",
    description: "Description for sample wish 7.",
    shopURL: "https://example.com/item7",
    price: 448.93,
    currency: "USD",
    isArchived: true,
    ownerId: "user2",
    bookerId: null,
    isBooked: false,
    wishlistId: "wishlist5",
    imageURL:
      "https://anyplaceholder.com/placeholder?width=848&height=617&bg=63ECC766&color=fff&text=wish+7&fontSize=21&radius=2&format=png&retina=true",
    isPrivate: true,
    canReadId: [],
    canEditId: [],
  },
  {
    $id: "wish8",
    $collectionId: "wishes",
    $databaseId: "mainDB",
    $createdAt: "2025-07-18T10:07:00Z",
    $updatedAt: "2025-07-18T10:07:00Z",
    $permissions: [],
    title: "Sample Wish Title 8",
    description: "Description for sample wish 8.",
    shopURL: "https://example.com/item8",
    price: 370.7,
    currency: "USD",
    isArchived: false,
    ownerId: "user2",
    bookerId: "user5",
    isBooked: true,
    wishlistId: "wishlist4",
    imageURL:
      "https://anyplaceholder.com/placeholder?width=797&height=586&bg=03C0C366&color=fff&text=wish+8&fontSize=21&radius=14&format=png&retina=true",
    isPrivate: true,
    canReadId: ["user3", "user1"],
    canEditId: [],
  },
  {
    $id: "wish9",
    $collectionId: "wishes",
    $databaseId: "mainDB",
    $createdAt: "2025-07-18T10:08:00Z",
    $updatedAt: "2025-07-18T10:08:00Z",
    $permissions: [],
    title: "Sample Wish Title 9",
    description: "Description for sample wish 9.",
    shopURL: "https://example.com/item9",
    price: 407.81,
    currency: "USD",
    isArchived: true,
    ownerId: "user9",
    bookerId: "user4",
    isBooked: true,
    wishlistId: "wishlist1",
    imageURL:
      "https://anyplaceholder.com/placeholder?width=704&height=570&bg=64702C66&color=fff&text=wish+9&fontSize=22&radius=2&format=png&retina=true",
    isPrivate: false,
    canReadId: [],
    canEditId: [],
  },
  {
    $id: "wish10",
    $collectionId: "wishes",
    $databaseId: "mainDB",
    $createdAt: "2025-07-18T10:09:00Z",
    $updatedAt: "2025-07-18T10:09:00Z",
    $permissions: [],
    title: "Sample Wish Title 10",
    description: "Description for sample wish 10.",
    shopURL: "https://example.com/item10",
    price: 189.74,
    currency: "USD",
    isArchived: true,
    ownerId: "user10",
    bookerId: "user3",
    isBooked: true,
    wishlistId: "wishlist4",
    imageURL:
      "https://anyplaceholder.com/placeholder?width=889&height=612&bg=B534A066&color=fff&text=wish+10&fontSize=28&radius=13&format=png&retina=true",
    isPrivate: false,
    canReadId: ["user4"],
    canEditId: ["user4"],
  },
  {
    $id: "wish11",
    $collectionId: "wishes",
    $databaseId: "mainDB",
    $createdAt: "2025-07-18T10:10:00Z",
    $updatedAt: "2025-07-18T10:10:00Z",
    $permissions: [],
    title: "Sample Wish Title 11",
    description: "Description for sample wish 11.",
    shopURL: "https://example.com/item11",
    price: 496.41,
    currency: "USD",
    isArchived: false,
    ownerId: "user4",
    bookerId: null,
    isBooked: true,
    wishlistId: "wishlist5",
    imageURL:
      "https://anyplaceholder.com/placeholder?width=724&height=656&bg=72988A66&color=fff&text=wish+11&fontSize=28&radius=1&format=png&retina=true",
    isPrivate: true,
    canReadId: ["user2"],
    canEditId: ["user6"],
  },
  {
    $id: "wish12",
    $collectionId: "wishes",
    $databaseId: "mainDB",
    $createdAt: "2025-07-18T10:11:00Z",
    $updatedAt: "2025-07-18T10:11:00Z",
    $permissions: [],
    title: "Sample Wish Title 12",
    description: "Description for sample wish 12.",
    shopURL: "https://example.com/item12",
    price: 433.8,
    currency: "USD",
    isArchived: false,
    ownerId: "user8",
    bookerId: null,
    isBooked: true,
    wishlistId: "wishlist5",
    imageURL:
      "https://anyplaceholder.com/placeholder?width=782&height=608&bg=8261D866&color=fff&text=wish+12&fontSize=23&radius=10&format=png&retina=true",
    isPrivate: true,
    canReadId: ["user6", "user1"],
    canEditId: ["user8", "user7"],
  },
  {
    $id: "wish13",
    $collectionId: "wishes",
    $databaseId: "mainDB",
    $createdAt: "2025-07-18T10:12:00Z",
    $updatedAt: "2025-07-18T10:12:00Z",
    $permissions: [],
    title: "Sample Wish Title 13",
    description: "Description for sample wish 13.",
    shopURL: "https://example.com/item13",
    price: 124.83,
    currency: "USD",
    isArchived: true,
    ownerId: "user3",
    bookerId: "user5",
    isBooked: true,
    wishlistId: "wishlist3",
    imageURL:
      "https://anyplaceholder.com/placeholder?width=758&height=553&bg=614DC566&color=fff&text=wish+13&fontSize=28&radius=0&format=png&retina=true",
    isPrivate: false,
    canReadId: [],
    canEditId: ["user7"],
  },
  {
    $id: "wish14",
    $collectionId: "wishes",
    $databaseId: "mainDB",
    $createdAt: "2025-07-18T10:13:00Z",
    $updatedAt: "2025-07-18T10:13:00Z",
    $permissions: [],
    title: "Sample Wish Title 14",
    description: "Description for sample wish 14.",
    shopURL: "https://example.com/item14",
    price: 474.79,
    currency: "USD",
    isArchived: false,
    ownerId: "user5",
    bookerId: "user3",
    isBooked: true,
    wishlistId: "wishlist5",
    imageURL:
      "https://anyplaceholder.com/placeholder?width=802&height=535&bg=4A5DCA66&color=fff&text=wish+14&fontSize=23&radius=3&format=png&retina=true",
    isPrivate: false,
    canReadId: ["user4"],
    canEditId: [],
  },
  {
    $id: "wish15",
    $collectionId: "wishes",
    $databaseId: "mainDB",
    $createdAt: "2025-07-18T10:14:00Z",
    $updatedAt: "2025-07-18T10:14:00Z",
    $permissions: [],
    title: "Sample Wish Title 15",
    description: "Description for sample wish 15.",
    shopURL: "https://example.com/item15",
    price: 476.39,
    currency: "USD",
    isArchived: false,
    ownerId: "user6",
    bookerId: null,
    isBooked: false,
    wishlistId: "wishlist5",
    imageURL:
      "https://anyplaceholder.com/placeholder?width=809&height=516&bg=D63C6066&color=fff&text=wish+15&fontSize=23&radius=14&format=png&retina=true",
    isPrivate: false,
    canReadId: [],
    canEditId: ["user8"],
  },
  {
    $id: "wish16",
    $collectionId: "wishes",
    $databaseId: "mainDB",
    $createdAt: "2025-07-18T10:15:00Z",
    $updatedAt: "2025-07-18T10:15:00Z",
    $permissions: [],
    title: "Sample Wish Title 16",
    description: "Description for sample wish 16.",
    shopURL: "https://example.com/item16",
    price: 79.08,
    currency: "USD",
    isArchived: false,
    ownerId: "user2",
    bookerId: null,
    isBooked: false,
    wishlistId: "wishlist3",
    imageURL:
      "https://anyplaceholder.com/placeholder?width=805&height=644&bg=E2C36066&color=fff&text=wish+16&fontSize=32&radius=8&format=png&retina=true",
    isPrivate: true,
    canReadId: ["user10"],
    canEditId: ["user1"],
  },
  {
    $id: "wish17",
    $collectionId: "wishes",
    $databaseId: "mainDB",
    $createdAt: "2025-07-18T10:16:00Z",
    $updatedAt: "2025-07-18T10:16:00Z",
    $permissions: [],
    title: "Sample Wish Title 17",
    description: "Description for sample wish 17.",
    shopURL: "https://example.com/item17",
    price: 192.96,
    currency: "USD",
    isArchived: true,
    ownerId: "user9",
    bookerId: null,
    isBooked: false,
    wishlistId: "wishlist5",
    imageURL:
      "https://anyplaceholder.com/placeholder?width=774&height=605&bg=56757E66&color=fff&text=wish+17&fontSize=25&radius=2&format=png&retina=true",
    isPrivate: true,
    canReadId: [],
    canEditId: ["user7"],
  },
  {
    $id: "wish18",
    $collectionId: "wishes",
    $databaseId: "mainDB",
    $createdAt: "2025-07-18T10:17:00Z",
    $updatedAt: "2025-07-18T10:17:00Z",
    $permissions: [],
    title: "Sample Wish Title 18",
    description: "Description for sample wish 18.",
    shopURL: "https://example.com/item18",
    price: 456.13,
    currency: "USD",
    isArchived: false,
    ownerId: "user4",
    bookerId: null,
    isBooked: false,
    wishlistId: "wishlist3",
    imageURL:
      "https://anyplaceholder.com/placeholder?width=773&height=693&bg=97908A66&color=fff&text=wish+18&fontSize=32&radius=13&format=png&retina=true",
    isPrivate: false,
    canReadId: [],
    canEditId: ["user4"],
  },
  {
    $id: "wish19",
    $collectionId: "wishes",
    $databaseId: "mainDB",
    $createdAt: "2025-07-18T10:18:00Z",
    $updatedAt: "2025-07-18T10:18:00Z",
    $permissions: [],
    title: "Sample Wish Title 19",
    description: "Description for sample wish 19.",
    shopURL: "https://example.com/item19",
    price: 101.7,
    currency: "USD",
    isArchived: false,
    ownerId: "user7",
    bookerId: "user4",
    isBooked: true,
    wishlistId: "wishlist4",
    imageURL:
      "https://anyplaceholder.com/placeholder?width=825&height=563&bg=13FF5966&color=fff&text=wish+19&fontSize=31&radius=4&format=png&retina=true",
    isPrivate: true,
    canReadId: [],
    canEditId: ["user1", "user7"],
  },
  {
    $id: "wish20",
    $collectionId: "wishes",
    $databaseId: "mainDB",
    $createdAt: "2025-07-18T10:19:00Z",
    $updatedAt: "2025-07-18T10:19:00Z",
    $permissions: [],
    title: "Sample Wish Title 20",
    description: "Description for sample wish 20.",
    shopURL: "https://example.com/item20",
    price: 76.27,
    currency: "USD",
    isArchived: false,
    ownerId: "user9",
    bookerId: "user2",
    isBooked: false,
    wishlistId: "wishlist3",
    imageURL:
      "https://anyplaceholder.com/placeholder?width=852&height=630&bg=5FC03F66&color=fff&text=wish+20&fontSize=29&radius=10&format=png&retina=true",
    isPrivate: false,
    canReadId: ["user9", "user4"],
    canEditId: [],
  },
  {
    $id: "wish21",
    $collectionId: "wishes",
    $databaseId: "mainDB",
    $createdAt: "2025-07-18T10:20:00Z",
    $updatedAt: "2025-07-18T10:20:00Z",
    $permissions: [],
    title: "Sample Wish Title 21",
    description: "Description for sample wish 21.",
    shopURL: "https://example.com/item21",
    price: 254.96,
    currency: "USD",
    isArchived: false,
    ownerId: "user6",
    bookerId: null,
    isBooked: false,
    wishlistId: "wishlist3",
    imageURL:
      "https://anyplaceholder.com/placeholder?width=737&height=522&bg=A83F9D66&color=fff&text=wish+21&fontSize=28&radius=8&format=png&retina=true",
    isPrivate: false,
    canReadId: ["user5"],
    canEditId: [],
  },
  {
    $id: "wish22",
    $collectionId: "wishes",
    $databaseId: "mainDB",
    $createdAt: "2025-07-18T10:21:00Z",
    $updatedAt: "2025-07-18T10:21:00Z",
    $permissions: [],
    title: "Sample Wish Title 22",
    description: "Description for sample wish 22.",
    shopURL: "https://example.com/item22",
    price: 29.76,
    currency: "USD",
    isArchived: false,
    ownerId: "user4",
    bookerId: "user10",
    isBooked: false,
    wishlistId: "wishlist5",
    imageURL:
      "https://anyplaceholder.com/placeholder?width=726&height=514&bg=B5972866&color=fff&text=wish+22&fontSize=25&radius=1&format=png&retina=true",
    isPrivate: false,
    canReadId: ["user7", "user4"],
    canEditId: [],
  },
  {
    $id: "wish23",
    $collectionId: "wishes",
    $databaseId: "mainDB",
    $createdAt: "2025-07-18T10:22:00Z",
    $updatedAt: "2025-07-18T10:22:00Z",
    $permissions: [],
    title: "Sample Wish Title 23",
    description: "Description for sample wish 23.",
    shopURL: "https://example.com/item23",
    price: 349.45,
    currency: "USD",
    isArchived: false,
    ownerId: "user3",
    bookerId: null,
    isBooked: true,
    wishlistId: "wishlist1",
    imageURL:
      "https://anyplaceholder.com/placeholder?width=883&height=690&bg=9C325E66&color=fff&text=wish+23&fontSize=31&radius=4&format=png&retina=true",
    isPrivate: true,
    canReadId: [],
    canEditId: ["user2"],
  },
  {
    $id: "wish24",
    $collectionId: "wishes",
    $databaseId: "mainDB",
    $createdAt: "2025-07-18T10:23:00Z",
    $updatedAt: "2025-07-18T10:23:00Z",
    $permissions: [],
    title: "Sample Wish Title 24",
    description: "Description for sample wish 24.",
    shopURL: "https://example.com/item24",
    price: 152.61,
    currency: "USD",
    isArchived: false,
    ownerId: "user2",
    bookerId: "user7",
    isBooked: true,
    wishlistId: "wishlist3",
    imageURL:
      "https://anyplaceholder.com/placeholder?width=741&height=675&bg=07584266&color=fff&text=wish+24&fontSize=26&radius=12&format=png&retina=true",
    isPrivate: false,
    canReadId: ["user2", "user8"],
    canEditId: ["user7"],
  },
  {
    $id: "wish25",
    $collectionId: "wishes",
    $databaseId: "mainDB",
    $createdAt: "2025-07-18T10:24:00Z",
    $updatedAt: "2025-07-18T10:24:00Z",
    $permissions: [],
    title: "Sample Wish Title 25",
    description: "Description for sample wish 25.",
    shopURL: "https://example.com/item25",
    price: 49.51,
    currency: "USD",
    isArchived: false,
    ownerId: "user5",
    bookerId: null,
    isBooked: false,
    wishlistId: "wishlist1",
    imageURL:
      "https://anyplaceholder.com/placeholder?width=717&height=508&bg=774E6766&color=fff&text=wish+25&fontSize=26&radius=5&format=png&retina=true",
    isPrivate: false,
    canReadId: [],
    canEditId: ["user6"],
  },
  {
    $id: "wish26",
    $collectionId: "wishes",
    $databaseId: "mainDB",
    $createdAt: "2025-07-18T10:25:00Z",
    $updatedAt: "2025-07-18T10:25:00Z",
    $permissions: [],
    title: "Sample Wish Title 26",
    description: "Description for sample wish 26.",
    shopURL: "https://example.com/item26",
    price: 226.9,
    currency: "USD",
    isArchived: false,
    ownerId: "user9",
    bookerId: null,
    isBooked: false,
    wishlistId: "wishlist1",
    imageURL:
      "https://anyplaceholder.com/placeholder?width=725&height=615&bg=BAA5B666&color=fff&text=wish+26&fontSize=26&radius=0&format=png&retina=true",
    isPrivate: true,
    canReadId: ["user1", "user5"],
    canEditId: ["user9"],
  },
  {
    $id: "wish27",
    $collectionId: "wishes",
    $databaseId: "mainDB",
    $createdAt: "2025-07-18T10:26:00Z",
    $updatedAt: "2025-07-18T10:26:00Z",
    $permissions: [],
    title: "Sample Wish Title 27",
    description: "Description for sample wish 27.",
    shopURL: "https://example.com/item27",
    price: 460.72,
    currency: "USD",
    isArchived: false,
    ownerId: "user10",
    bookerId: null,
    isBooked: true,
    wishlistId: "wishlist1",
    imageURL:
      "https://anyplaceholder.com/placeholder?width=742&height=565&bg=9C41DA66&color=fff&text=wish+27&fontSize=24&radius=10&format=png&retina=true",
    isPrivate: false,
    canReadId: ["user1", "user8"],
    canEditId: ["user4"],
  },
  {
    $id: "wish28",
    $collectionId: "wishes",
    $databaseId: "mainDB",
    $createdAt: "2025-07-18T10:27:00Z",
    $updatedAt: "2025-07-18T10:27:00Z",
    $permissions: [],
    title: "Sample Wish Title 28",
    description: "Description for sample wish 28.",
    shopURL: "https://example.com/item28",
    price: 118.02,
    currency: "USD",
    isArchived: false,
    ownerId: "user10",
    bookerId: "user4",
    isBooked: false,
    wishlistId: "wishlist5",
    imageURL:
      "https://anyplaceholder.com/placeholder?width=739&height=544&bg=A1AAEE66&color=fff&text=wish+28&fontSize=24&radius=4&format=png&retina=true",
    isPrivate: true,
    canReadId: [],
    canEditId: ["user10", "user8"],
  },
  {
    $id: "wish29",
    $collectionId: "wishes",
    $databaseId: "mainDB",
    $createdAt: "2025-07-18T10:28:00Z",
    $updatedAt: "2025-07-18T10:28:00Z",
    $permissions: [],
    title: "Sample Wish Title 29",
    description: "Description for sample wish 29.",
    shopURL: "https://example.com/item29",
    price: 368.19,
    currency: "USD",
    isArchived: false,
    ownerId: "user3",
    bookerId: "user1",
    isBooked: false,
    wishlistId: "wishlist2",
    imageURL:
      "https://anyplaceholder.com/placeholder?width=778&height=500&bg=7EE6D166&color=fff&text=wish+29&fontSize=21&radius=12&format=png&retina=true",
    isPrivate: false,
    canReadId: ["user5", "user7"],
    canEditId: ["user4"],
  },
  {
    $id: "wish30",
    $collectionId: "wishes",
    $databaseId: "mainDB",
    $createdAt: "2025-07-18T10:29:00Z",
    $updatedAt: "2025-07-18T10:29:00Z",
    $permissions: [],
    title: "Sample Wish Title 30",
    description: "Description for sample wish 30.",
    shopURL: "https://example.com/item30",
    price: 474.65,
    currency: "USD",
    isArchived: false,
    ownerId: "user4",
    bookerId: "user8",
    isBooked: false,
    wishlistId: "wishlist1",
    imageURL:
      "https://anyplaceholder.com/placeholder?width=716&height=617&bg=A8B1EA66&color=fff&text=wish+30&fontSize=20&radius=11&format=png&retina=true",
    isPrivate: true,
    canReadId: ["user2"],
    canEditId: [],
  },
];

export const wishlists = [
  {
    $id: "wishlist1",
    $collectionId: "wishlists",
    $databaseId: "mainDB",
    $createdAt: "2025-07-18T09:00:00Z",
    $updatedAt: "2025-07-18T09:00:00Z",
    $permissions: [],
    title: "Tech Gadgets Wishlist",
    description: "All the latest tech I want to own.",
    ownerId: "user1",
    wishesId: ["wish1", "wish5", "wish7"],
    isPrivate: false,
    canReadId: ["user2"],
    canEditId: ["user1"],
    coverImagesURL: [
      "https://anyplaceholder.com/placeholder?width=800&height=600&bg=1122cc66&color=fff&text=cover+1-1&fontSize=24&radius=5&format=png&retina=true",
    ],
  },
  {
    $id: "wishlist2",
    $collectionId: "wishlists",
    $databaseId: "mainDB",
    $createdAt: "2025-07-18T09:05:00Z",
    $updatedAt: "2025-07-18T09:05:00Z",
    $permissions: [],
    title: "Books To Read",
    description: "Fiction and non-fiction books on my radar.",
    ownerId: "user3",
    wishesId: ["wish3", "wish12"],
    isPrivate: false,
    canReadId: ["user4"],
    canEditId: [],
    coverImagesURL: [
      "https://anyplaceholder.com/placeholder?width=750&height=500&bg=dd884466&color=fff&text=cover+2-1&fontSize=20&radius=4&format=png&retina=true",
    ],
  },
  {
    $id: "wishlist3",
    $collectionId: "wishlists",
    $databaseId: "mainDB",
    $createdAt: "2025-07-18T09:10:00Z",
    $updatedAt: "2025-07-18T09:10:00Z",
    $permissions: [],
    title: "Birthday Wishlist",
    description: "What I’d love for my next birthday!",
    ownerId: "user2",
    wishesId: ["wish2", "wish9", "wish14"],
    isPrivate: true,
    canReadId: ["user5", "user6"],
    canEditId: ["user2"],
    coverImagesURL: [
      "https://anyplaceholder.com/placeholder?width=820&height=600&bg=ee334466&color=fff&text=cover+3-1&fontSize=26&radius=7&format=png&retina=true",
      "https://anyplaceholder.com/placeholder?width=800&height=500&bg=66bbcc66&color=fff&text=cover+3-2&fontSize=22&radius=4&format=png&retina=true",
    ],
  },
  {
    $id: "wishlist4",
    $collectionId: "wishlists",
    $databaseId: "mainDB",
    $createdAt: "2025-07-18T09:15:00Z",
    $updatedAt: "2025-07-18T09:15:00Z",
    $permissions: [],
    title: "Home Decor Ideas",
    description: "Everything for making home cozier.",
    ownerId: "user4",
    wishesId: ["wish10", "wish20", "wish22", "wish30"],
    isPrivate: false,
    canReadId: [],
    canEditId: ["user4"],
    coverImagesURL: [
      "https://anyplaceholder.com/placeholder?width=860&height=550&bg=cc663366&color=fff&text=cover+4-1&fontSize=28&radius=6&format=png&retina=true",
    ],
  },
  {
    $id: "wishlist5",
    $collectionId: "wishlists",
    $databaseId: "mainDB",
    $createdAt: "2025-07-18T09:20:00Z",
    $updatedAt: "2025-07-18T09:20:00Z",
    $permissions: [],
    title: "Fitness Goals",
    description: "Gear and gadgets for a healthier lifestyle.",
    ownerId: "user5",
    wishesId: ["wish4", "wish8", "wish15"],
    isPrivate: true,
    canReadId: ["user3"],
    canEditId: [],
    coverImagesURL: [
      "https://anyplaceholder.com/placeholder?width=800&height=600&bg=00aa8866&color=fff&text=cover+5-1&fontSize=25&radius=5&format=png&retina=true",
    ],
  },
];
